version: '3.9'
services:
  nginx60:
    image: nginx
    volumes:
      - ./src/60:/usr/share/nginx/html:ro
    ports:
    - "60:80"
  nginx90:
    image: nginx
    volumes:
      - ./src/90:/usr/share/nginx/html:ro
    ports:
    - "90:80"